# config for camera worker

account: '06e5a032-2d26-43ef-b10d-56906a98fb59'
zone: '1'
events:
  - eventType: 'videoloss'
    eventState: 'active'
    siaCode: 'AP'
  
  - eventType: 'videoloss'
    eventState: 'inactive'
    siaCode: 'HA'

  - eventType: 'videoloss'
    eventState: 'inactive'
    siaCode: 'XX'